### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/windows-inventory-agent#1]
Create gh-pages as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

**Comment by Naylin15** [comment]
Hi, @ajsb85

I'm checking this issue and for what I could see these repositories already have project sites, we can update the content in the index since some of them have the readme information

I think we can close the following issues besides this one, unless something else is required?

* [#2](https://github.com/flyve-mdm/windows-mdm-agent/issues/2)
* [#2](https://github.com/flyve-mdm/windows-inventory-library/issues/2)
* [#2](https://github.com/flyve-mdm/windows-mdm-dashboard/issues/2)
* [#1](https://github.com/flyve-mdm/blackberry-inventory-library/issues/1)
* [#2](https://github.com/flyve-mdm/blackberry-mdm-dashboard/issues/2)
* [#2](https://github.com/flyve-mdm/backend-tests/issues/2)
* [#4](https://github.com/flyve-mdm/blackberry-mdm-agent/issues/4)

Thank you
